# Generated by Django 4.0.5 on 2022-06-06 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='buildingName',
            field=models.CharField(max_length=100),
        ),
    ]
